measure:
  key: book
  name: Posts With Titles Containing "Night"
filters:
  - key: title
    criteria:
      operator: contains
      value: Night
dimensions:
  - author
  - title
#  - key: created_at
#    granularity: day